project:
  type: website

website:
  title: "Projet Volant"
  navbar:
    left:
      - href: index.qmd
        text: Accueil
      - index.qmd
      - href: regex.qmd
      - href: nested/nested_file.qmd
        text: "fichier nested"

format:
  html:
    theme: darksly
    # css: styles.css
    toc: true
